/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.edu.uni.programacion.views.commons;

import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author yasser.membreno
 */
public class LeftMenuPanel extends javax.swing.JPanel {

    /**
     * Creates new form LeftMenuPanel
     */
    private String title;
    
    public LeftMenuPanel() {
        title = "PaneTitle";
        initComponents();
    }
    
    public LeftMenuPanel(String title){
        this.title = title;        
        initComponents();
    }

    public void setContentPane(JPanel contentPane) {
        this.contentPane = contentPane;
    }

    public void setTitleLabel(JLabel titleLabel) {
        this.titleLabel = titleLabel;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePane = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        contentPane = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        titlePane.setBackground(new java.awt.Color(204, 204, 204));

        titleLabel.setText("Title");
        titleLabel.setText(this.title);
        titlePane.add(titleLabel);

        add(titlePane, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout contentPaneLayout = new javax.swing.GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
        );

        add(contentPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPane;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePane;
    // End of variables declaration//GEN-END:variables
}
